name: WH64 Windows test build

on:
  push:
    branches:
      - wh64-windows-fix

env:
  BUILD_TYPE: Release
  EXT_BASE: ${{ github.workspace }}

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2025
    name: Build GOnnect (Windows)

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: 'true'
          submodules: 'recursive'

      - name: Prepare
        uses: ./.github/actions/prepare-windows

      - name: Configure CMake
        shell: cmd
        run: cmake --preset conan-default -DENABLE_MSGRAPH=ON -DMS_APPLICATION_IDENTIFIER=
        env:
          NSIS_USE_FAST_COMPRESSION: "1"

      - name: Build application
        run: cmake --build --preset conan-release

      - name: Build installer
        run: cd build && cpack ${{ github.workspace }}

      - name: Save installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: windows-installer-uri-fix
          compression-level: 0
          path: build/GOnnect*.exe
